apiVersion: v1
kind: ConfigMap
metadata:
  name: 3l-config
  labels:
    app: 3l
data:
  POSTGRES_DB: books
  POSTGRES_USER: sample
  POSTGRES_PASSWORD: changeme
  FLASK_ENV: development
  APP_SETTINGS: project.config.DevelopmentConfig
